NVDB Vegpunkter: Bug fix in notebook
svvsaga/notebooks-public pull request #20
Opened 2023-11-27 12:50 UTC by KennethSVV

2023-11-27 12:50 UTC, KennethSVV reviewed
Bug fixed

2023-11-27 14:03 UTC, LangdalP requested changes

2023-11-27 14:03 UTC, LangdalP commented on notebooks/bigquery:saga-data.nvdb.nvdb_vegpunkter.ipynb
> +    "bq_job_project = 'saga-kenang-sandbox-yuam'"
```suggestion
    "bq_job_project = ''"
```

2023-11-28 08:20 UTC, LangdalP approved these changes
Ser bra ut.

2023-11-28 08:20 UTC, merged